version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "setup.py" }}-{{ checksum "xain/config.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh
            sudo apt-get update && sudo apt-get install -y clang-format-8

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "setup.py" }}-{{ checksum "xain/config.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            ./scripts/test.sh
  tests_slow:
    docker:
      - image: circleci/python:3.7
    resource_class: xlarge
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "setup.py" }}-{{ checksum "xain/config.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "setup.py" }}-{{ checksum "xain/config.py" }}

      - run:
          name: run tests slow
          command: |
            . venv/bin/activate
            ./scripts/test_slow.sh

  tests_benchmark:
    docker:
      - image: circleci/python:3.7
    resource_class: large
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "setup.py" }}-{{ checksum "xain/config.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            ./scripts/setup.sh

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "setup.py" }}-{{ checksum "xain/config.py" }}

      - run:
          name: run tests benchmark
          command: |
            . venv/bin/activate
            python -m xain.benchmark.exec --group_name=ci-test-group --task_name=ci-test-task --dataset=fashion-mnist-100p-iid-balanced --model=blog_cnn --R=2 --E=2 --C=0.02 --B=64

workflows:
  version: 2.1
  qa:
    jobs:
      - tests
      - tests_slow
      - tests_benchmark
