version: "3.7"
services:
  minio:
    image: minio/minio # Stable minio
    volumes:
      - minio-data:/data
    networks:
      - xain-fl-rs
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    ports:
      - "9000:9000"

  redis:
    image: redis:5.0.9
    hostname: redis
    volumes:
      - redis-data:/data
    networks:
      - xain-fl-rs
    ports:
      - "6379:6379"

volumes:
  minio-data:
  redis-data:

networks:
  xain-fl-rs:
