[package]
name = "xain-fl"
version = "0.1.0"
authors = ["little-dude <corentinhenry@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.8.1", features = ["v4", "serde"] }
futures = "0.3.4"
tokio = { version = "0.2.13", features = ["rt-core", "rt-threaded", "tcp", "time", "macros", "signal", "sync", "stream"] }
warp = { version = "0.2.2", default-features = false, features = ["multipart"] }
derive_more = { version = "0.99.3", default-features = false, features = [ "display", "from" ] }
rand = "0.7.3"
tarpc = { version = "0.20.0", features = [ "full" ] }
serde = { version = "1.0.104", features = [ "derive" ] }
pyo3 = "0.9.0-alpha.1"
tokio-serde = { version = "0.6.0", features = [ "json" ] }
stubborn-io = "0.1.8"
bytes = "0.5.4"
config = { version = "0.10.1", default-features = false, features = [ "toml" ] }
clap = "2.33.0"
influxdb = "0.0.6"
thiserror = "1.0.11"
anyhow = "1.0.26"
tracing = "0.1.13"
# tracing-futures = "0.2.3"
tracing-subscriber = "0.2.3"

[[bin]]
name = "coordinator"
path = "src/bin/coordinator.rs"

[[bin]]
name = "aggregator"
path = "src/bin/aggregator.rs"
