[workspace]
members = [
    "xaynet",
    "xaynet-core",
    "xaynet-macros",
    "xaynet-mobile",
    "xaynet-server",
    "xaynet-sdk",

    # internals
    "benches",
    "examples",
]

[workspace.metadata]
# minimum supported rust version
msrv = "1.46.0"
