[log]
filter = "xaynet=debug,http=warn,info"

[api]
bind_address = "0.0.0.0:8081"
tls_certificate = "/app/ssl/tls.pem"
tls_key = "/app/ssl/tls.key"
# tls_client_auth = "/app/ssl/trust_anchor.pem"

[pet.sum]
prob = 0.01

[pet.sum.count]
min = 1
max = 100

[pet.sum.time]
min = 5
max = 3600

[pet.update]
prob = 0.1

[pet.update.count]
min = 3
max = 10000

[pet.update.time]
min = 10
max = 3600

[pet.sum2.count]
min = 1
max = 100

[pet.sum2.time]
min = 5
max = 3600

[mask]
group_type = "Prime"
data_type = "F32"
bound_type = "B0"
model_type = "M3"

[model]
length = 4

[metrics.influxdb]
url = "http://influxdb:8086"
db = "metrics"

[redis]
url = "redis://redis"

[s3]
access_key = "minio"
secret_access_key = "minio123"
region = ["minio", "http://minio:9000"]

[restore]
enable = true
