[logging]
level = "debug"
telemetry = { jaeger_endpoint = "jaeger:6831", service_name = "aggregator" }

[aggregation.python]
module = "xain_aggregators.weighted_average"
class = "Aggregator"

[api]
bind_address = "0.0.0.0:8082"

[rpc]
bind_address = "0.0.0.0:6666"
coordinator_address = "coordinator:5555"
