# An example configfiguration file.
# The values that are used for the optional keys correspond to their default values.

# (Optional)
[server]
# (Optional) Address to listen on for incoming gRPC connections
host = "localhost"
# (Optional) Port to listen on for incoming gRPC connections
port = 50051

# (Optional)
[server.grpc_options]
# More information about all available gRPC options can be found here:
# https://grpc.github.io/grpc/cpp/group__grpc__arg__keys.html#ga813f94f9ac3174571dd712c96cdbbdc1

# Example
# Maximum message length that the channel can receive. -1 means unlimited.
# "grpc.max_receive_message_length" = -1

# (Required)
[ai]
# (Required) Number of global rounds the model is going to be trained for. This
# must be a positive integer.
rounds = 2
# (Required) Number of local epochs per round
epochs = 1
# (Optional) Minimum number of participants to be selected for a round.
min_participants = 1
# (Optional) Fraction of total clients that participate in a training round. This
# must be a float between 0 and 1.
fraction_participants = 1.0

# (Required)
[storage]
# (Required) URL to the storage service to use
endpoint = "http://minio-dev:9000"
# (Required) Name of the bucket for storing the global model weights
global_weights_bucket = "xain-fl-aggregated-weights"
# (Required) Name of the bucket for retrieving the local model weights
local_weights_bucket = "xain-fl-participants-weights"
# (Required) AWS access key ID to use to authenticate to the storage service
access_key_id = "minio"
# (Required) AWS secret access to use to authenticate to the storage service
secret_access_key = "minio123"

# (Optional)
[logging]
# (Optional) The log level can be one of "notset", "debug", "info", "warning",
# "error" and "critical".
level = "info"
# (Optional) 
console = false
# (Optional) 
third_party = false

# (Optional)
[metrics]
# (Optional) If `true`, store metrics in InfluxDB, otherwise not.
enable = false
# (Optional) The hostname to connect to InfluxDB.
host = "localhost"
# (Optional) The port of InfluxDB.
port = 8086
# (Optional) The name of the InfluxDB user.
user = "root"
# (Optional) The password of the InfluxDB user.
password = "root"
# (Optional) The name of the database.
db_name = "metrics"
