filter = "test_case=debug,e2e=debug,xaynet=info"

[k8s]
namespace = "xaynet"
coordinator_pod_label = "app=coordinator"
coordinator_image = "xaynetwork/xaynet:development"
influxdb_pod_name = "influxdb-0"
redis_pod_name = "redis-master-0"
s3_pod_label = "minio"

[coordinator]
config = "src/bin/test_case_1/config.toml"

[influx]
url = "http://localhost:8086"
db = "metrics"

[redis]
url = "redis://localhost/"

[s3]
access_key = "minio"
secret_access_key = "minio123"
region = ["minio", "http://localhost:9000"]

[api_client]
address = "http://localhost:8081"
# tls
# address = "https://dev-coordinator.xayn.com"
# certificates = [ "src/bin/test_case_1/dev-coordinator-xayn-com.pem" ]
# identity =
