apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

images:
- name: coordinator
  newName: xain/xain-fl
  newTag: development

configMapGenerator:
- name: config-toml
  files:
  - config-release-coordinator.toml

patchesStrategicMerge:
- history-limit.yaml
- config-volume-mount.yaml
resources:
- ../base
