apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

images:
  - name: coordinator
    newName: xaynetwork/xaynet
    newTag: development

configMapGenerator:
  - name: config-toml
    files:
    - config.toml

bases:
  - ../base

patchesStrategicMerge:
  - history-limit.yaml
  - config-volume-mount.yaml
resources:
  - ingress.yam
