name: Lint and test (development)

on:
  pull_request:
    branches:
      - development
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-dev-${{ hashFiles('setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -e .[dev]

      - name: black
        run: |
          black --check --exclude "xain_fl/cproto/.*_pb2.*" \
          setup.py conftest.py benchmarks examples xain_fl

      - name: isort
        run: |
          isort --check-only --indent=4 -rc setup.py conftest.py benchmarks \
          examples xain_fl

      - name: pylint
        run: |
          pylint --rcfile=pylint.ini benchmarks examples xain_fl

      - name: mypy
        continue-on-error: true
        run: |
          mypy benchmarks examples/* xain_fl

      - name: Sphinx check
        env:
          SPHINXOPTS: "-W"
        run: |
          cd docs/
          make docs

      - name: PyTest
        run: |
          pytest -v
