name: Lint and test (master)

on:
  pull_request:
    branches:
      - master

jobs:
  master_lint_and_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pip packages
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-master-${{ hashFiles('setup.py') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -e .[dev]

      - name: black
        run: |
          black --check setup.py xain_fl tests

      - name: isort
        run: |
          isort --check-only --diff --settings-path=.isort.cfg -rc setup.py xain_fl tests

      - name: pylint
        run: |
          pylint --rcfile=.pylintrc xain_fl tests

      - name: mypy
        run: |
          mypy xain_fl tests

      - name: Sphinx check
        env:
          SPHINXOPTS: "-W"
        run: |
          cd docs/
          make docs

      - name: PyTest
        run: |
          pytest -v

      # TODO: Add E2E tests here!!!

